FROM golang:1.19.3 as builder

RUN apt-get update && apt-get install -y git 

# Download ovn
RUN cd /opt/ && git clone -b v1.1.1 https://github.com/containernetworking/plugins

# Install ovn/ovs
RUN cd /opt/plugins && ./build_linux.sh

FROM alpine:3.16

RUN mkdir -p /opt/bin
COPY --from=builder /opt/plugins/bin/* /opt/bin/
